# Channel Mapping, based on:
# T7	CH01
# C3	CH02
# T8	CH05
# FC4	CH06
# FC3	CH09
# C4	CH10
# CP3	CH13
# CP4	CH14
#           1    2    3    4    5    6    7    8

channels: [
    Iz, PO9, PO10, O1, O2, P7, P3, Pz,
    P4, P8,  TP9,  TP10, CP5, CP1, CP2, CP6,
    T7, T8, C3, Cz, C4, FC5, FC1, FC2,
    FC6, FT9, FT10, F7, F3, Fz, F4, F8, ]
montage: easycap-M1

# Bandpass filter applied on raw signal
fmin: 1.5
fmax: 200

# Main frequencies to be notch'ed out
freqs_main: [50, 100, 150]

# Report output dir
report_dir: "/home/wgodefro/delme/test"
