# Channel Mapping, based on:
# T7	CH01
# C3	CH02
# T8	CH05
# FC4	CH06
# FC3	CH09
# C4	CH10
# CP3	CH13
# CP4	CH14
#           1    2    3    4    5    6    7    8
# channels: [ T7,  C3,  U3,  U4,  T8,  FC4, U7,  U8,
#             FC3, C4,  U11,  U12,  CP3, CP4, U15,  U16,
#             U17,  U18, U19, U20, U21, U22, U23, U24,
#             U25, U26, U27, U28, U29, U30, U31, U32 ]
#           1    2    3    4    5    6    7    8
# channels: [ Fp1, Fp2, F3, F4, C3, C4, P3, P4,
#             O1, O2, F7, F8, T7, T8, P7, P8,
#             Fz, Cz, Pz, Oz, FC1, FC2, CP1, CP2,
#             FC5, FC6, CP5, CP6, TP9, TP10, POz, Iz ]

channels: [
    "Iz", "PO9", "PO10", "O1", "O2", "P7", "P3", "Pz",
    "P4", "P8", "TP9", "TP10", "CP5", "CP1", "CP2", "CP6",
    "T7", "T8", "C3", "Cz", "C4", "FC5", "FC1", "FC2",
    "FC6", "FT9", "FT10", "F7", "F3", "Fz", "F4", "F8"
]

# Bandpass filter applied on raw signal
fmin: 1.5 
fmax: 499

# Main frequencies to be notch'ed out
freqs_main: [ 50, 100, 150, 200, 250, 300, 350, 400, 450]
